name: Debugging podman
# Make sure only one action triggers the job, otherwise pushing to a
# pull-request will run it twice.
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone Repository"
        uses: actions/checkout@v4
      - name: Run tests in podman
        run: podman info && make test-in-podman
